version: "3.9"
services:
  php:
    build: ./docker/php
    #image: php:8.1.9-cli
    ports:
      - "8080:8080"
    volumes:
      - ./php_listner/files:/app
    command: php -S 0.0.0.0:8080 -t /app
    working_dir: /app
    depends_on:
      - rabbit
  telebot:
    build: ./docker/telebot 
    volumes:
      - ./telebot:/usr/src/app/
    working_dir: /usr/src/app/
    command: python3 /usr/src/app/consumer.py
  rabbit:
    image: rabbitmq:3.10.7-management-alpine
    ports:
      - "15672:15672" # login and password guest
      - "5672:5672"
      - "5671:5671"
